// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUv_Qwaa9mzIW8lpmOC86GLKohpWOVbWY',
    appId: '1:60897175870:web:2aa5100fefe0c834b2246f',
    messagingSenderId: '60897175870',
    projectId: 'healthmate-a84d2',
    authDomain: 'healthmate-a84d2.firebaseapp.com',
    databaseURL:
        'https://healthmate-a84d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-a84d2.firebasestorage.app',
    measurementId: 'G-6KPD14M940',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFFIXjgnW-vqtvp8vcq-vOrJXvA-902I',
    appId: '1:60897175870:android:ae3addd877732e29b2246f',
    messagingSenderId: '60897175870',
    projectId: 'healthmate-a84d2',
    databaseURL:
        'https://healthmate-a84d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-a84d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCJBLiCpDZ49xGijk5AYdvsllbOfha6Ec',
    appId: '1:60897175870:ios:12800363bbded360b2246f',
    messagingSenderId: '60897175870',
    projectId: 'healthmate-a84d2',
    databaseURL:
        'https://healthmate-a84d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-a84d2.firebasestorage.app',
    iosBundleId: 'com.example.healthmateMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCJBLiCpDZ49xGijk5AYdvsllbOfha6Ec',
    appId: '1:60897175870:ios:12800363bbded360b2246f',
    messagingSenderId: '60897175870',
    projectId: 'healthmate-a84d2',
    databaseURL:
        'https://healthmate-a84d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-a84d2.firebasestorage.app',
    iosBundleId: 'com.example.healthmateMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUv_Qwaa9mzIW8lpmOC86GLKohpWOVbWY',
    appId: '1:60897175870:web:4db841aebad04367b2246f',
    messagingSenderId: '60897175870',
    projectId: 'healthmate-a84d2',
    authDomain: 'healthmate-a84d2.firebaseapp.com',
    databaseURL:
        'https://healthmate-a84d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthmate-a84d2.firebasestorage.app',
    measurementId: 'G-8Q95MBTE08',
  );
}
